version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_2201_ROSAProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/kvv
  gitUsername: kvv
  gitBranch: main
services:
- serviceName: project.siqa_2201_rosa.integrations:alertFS
  packages:
  - name: SIQA_2201_ROSAProject
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
